import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import ProtectedRoute from "@/components/auth/protectedRoute";
import { MenuUser } from "@/components/menu-user";
import { ModeToggle } from "@/components/modeToogle";
import { Menubar, MenubarContent, MenubarItem, MenubarMenu, MenubarTrigger } from "@/components/ui/menubar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { Separator } from "@radix-ui/react-separator";
import { Metadata } from "next";
import { getServerSession } from "next-auth";
import Image from "next/image";
import Link from "next/link";
import logo from '@/components/icons/logo.png'


export const metadata: Metadata = {
  title: "Cash Portal | CSWithBari",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions)
    const user = session?.user
      ? {
          name: session.user.name || "Student",
          email: session.user.email || "student@example.com",
          avatar: session.user.image || "/avatars/default.jpg",
          role: "Cash User",
        }
      : {
          name: "Guest",
          email: "guest@example.com",
          avatar: "/avatars/default.jpg",
          role: "guest",
        }
  return (
    <html lang="en">
      <body
      >
        <ProtectedRoute allowedRoles={["cash"]}>
          <SidebarProvider>
            <SidebarInset>
              {/* 🧭 Top Navigation Bar */}
              <header className="flex items-center justify-between h-16 border-b bg-background px-4 sm:px-6">
                {/* LEFT: Logo + Desktop Menu */}
                <div className="flex items-center gap-4">
                  {/* Mobile Hamburger Menu */}

                  {/* Logo */}
                  <Link href="/" className="flex items-center gap-2">
                    <Image
                      src={logo}
                      alt="CSWithBari Logo"
                      width={60}
                      height={60}
                      priority
                      className="rounded-md select-none"
                    />
                  </Link>

                  {/* Desktop Menubar */}
                  <Menubar className="hidden md:flex bg-transparent border-none shadow-none">
                    <MenubarMenu>
                      <MenubarTrigger>Cash Portal</MenubarTrigger>
                      <MenubarContent>
                        <MenubarItem >
                          <Link href="/dashboard/cash">Home</Link>
                        </MenubarItem>
                      </MenubarContent>

                    </MenubarMenu>
                    <MenubarMenu>
                      <MenubarTrigger>Orders</MenubarTrigger>
                      <MenubarContent>
                        <MenubarItem >
                          <Link href="/dashboard/cash/orders">History</Link>
                        </MenubarItem>
                      </MenubarContent>
                      
                    </MenubarMenu>
                  </Menubar>
                </div>

                {/* CENTER: Greeting */}
                <div className="absolute left-1/2 transform -translate-x-1/2 hidden md:flex items-center gap-2 text-sm">
                  <Separator orientation="vertical" className="h-4" />
                  
                </div>

                {/* RIGHT: User Menu + Theme */}
                <div className="flex items-center gap-4">
                  <MenuUser user={user} />
                  <ModeToggle />
                </div>
              </header>

              {/* 🌐 Main Page Content */}
              <main className="flex flex-1 flex-col gap-4 p-6">
                {children}
              </main>
            </SidebarInset>
          </SidebarProvider>
        </ProtectedRoute>
      </body>
    </html>
  );
}