// import { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Admin Dashboard | CSWithBari",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import { Metadata } from "next";
import { AppSidebar } from "@/components/app-sidebar";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { Breadcrumb } from "@/components/ui/breadcrumb";
import { Separator } from "@/components/ui/separator";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { ModeToggle } from "@/components/modeToogle";

export const metadata: Metadata = {
  title: "Admin Dashboard | CSWithBari",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          {/* Sidebar (Persistent across all dashboard pages) */}
          <AppSidebar />

          {/* Main Dashboard Content */}
          <SidebarInset>
            {/* Header (Constant across all pages) */}
            <header className="flex h-16 shrink-0 items-center gap-2 border-b">
              <div className="flex items-center gap-2 px-3">
                <SidebarTrigger />
                <ModeToggle />
                <Separator orientation="vertical" className="mr-2 h-4" />
                <Breadcrumb className="text-sm">
                  Welcome back, {session?.user?.name ?? "User"}
                </Breadcrumb>
              </div>
            </header>

            {/* Dynamic Page Content */}
            <main className="flex flex-1 flex-col gap-4 p-4">
              {children}
            </main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
