import { ModeToggle } from "@/components/modeToogle";
import { Breadcrumb } from "@/components/ui/breadcrumb";
import { Separator } from "@/components/ui/separator";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

import { Metadata } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "../../api/auth/[...nextauth]/route";
import { NavUser } from "@/components/nav-users";

export const metadata: Metadata = {
  title: "Dashboard | CSWithBari",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions);
    const user = session?.user || {
    name: "Guest",
    email: "guest@example.com",
    image: "/avatars/default.jpg",
  }
  return (
    
    <html lang="en">
      <body
      >
        <SidebarProvider>
          {/* Sidebar (Persistent across all dashboard pages) */}

          {/* Main Dashboard Content */}
          <SidebarInset>
            {/* Header (Constant across all pages) */}
          <header className="flex w-full h-16 items-center border-b px-4">
            <div className="flex w-full items-center justify-between">
              {/* Left side */}
              <div className="flex items-center gap-3">
                <ModeToggle />
                <Separator orientation="vertical" className="h-4" />
                <Breadcrumb className="text-sm">
                  Welcome back, {session?.user?.name ?? "User"}
                </Breadcrumb>
              </div>

              {/* Right side */}
              <NavUser user={user} />
            </div>
          </header>


            {/* Dynamic Page Content */}
            <main className="flex flex-1 flex-col gap-4 p-4">
              {children}
            </main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  ); 
}